# frozen_string_literal: true

# Blog Writer production renderer v1
# Generated by Blog Writer. The Markdown source remains the canonical editable
# document; this hook swaps Kramdown's conversion for the shared renderer output.
Jekyll::Hooks.register :posts, :post_convert do |post|
  rendered_path = post.data["blog_writer_rendered_body"]
  next unless rendered_path

  source_root = File.expand_path(post.site.source)
  rendered_file = File.expand_path(rendered_path, source_root)
  rendered_root = File.join(source_root, "_blog_writer") + File::SEPARATOR
  unless rendered_file.start_with?(rendered_root) && File.file?(rendered_file)
    raise Jekyll::Errors::FatalException, "Missing Blog Writer rendered body: #{rendered_path}"
  end

  post.content = File.read(rendered_file, encoding: "UTF-8")
end

Jekyll::Hooks.register :posts, :post_render do |post|
  next unless post.data["blog_writer_rendered_body"]

  stylesheet = "https://cdn.jsdelivr.net/npm/katex@0.16.47/dist/katex.min.css"
  post.output.sub!("</head>", %(<link rel="stylesheet" href="#{stylesheet}">
</head>))
end
